spring:
  application:
    name: rostering

  datasource:
    url: jdbc:mysql://localhost:3306/rostering
    username: root
    password: Khanh1995!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true